name: Create Docker Image

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: create Docker Image
        run: |
          IMAGE_TAG=$(echo ${{ github.ref }} | sed -e 's/refs\/tags\///')
          ./gradlew bootBuildImage --imageName=${{ secrets.REGISTRY_SERVER }}/batch_processing:$IMAGE_TAG .
          docker push ${{ secrets.REGISTRY_SERVER }}/batch_processing:$IMAGE_TAG
          docker tag ${{ secrets.REGISTRY_SERVER }}/batch_processing:$IMAGE_TAG ${{ secrets.REGISTRY_SERVER }}/batch_processing:latest
          docker push ${{ secrets.REGISTRY_SERVER }}/batch_processing:latest
